const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_INTERNAL_SERVER_ERROR = 500;
const CREATED = 201;
const ERROR_UNAUTHORIZED = 401;
const ERROR_MONGOOSE = 409;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_INTERNAL_SERVER_ERROR,
  CREATED,
  ERROR_UNAUTHORIZED,
  ERROR_MONGOOSE,
};
